# -*- coding: utf-8 -*-
"""2.1.deploy_question_answer_app-Copy1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ln1vrN3QTZNJAUTxpdRatGKgd_V6DXY9

#### Authentication
"""

import openai
import os
from secret_key import api_key
openai.api_key = api_key

"""#### Openai API Call"""

def qa_app(input_text):
    # Create a list of messages containing the user input
    messages = [
        {
            "role": "system",
            "content": "You will be provided with a question, and your task is to answer it correctly."
        },
        {
            "role": "user",
            "content": input_text
        }
    ]

    # Generate response from the model
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages,
        temperature=0,
        max_tokens=256
    )

    # Return the generated output
    return response['choices'][0]['message']['content']